apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: vaishnavi2010/easycrud1-jenkins:backend
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
